import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Navbar from "@/components/common/Navbar/Navbar";
import Footer from "@/components/common/Footer/Footer";
import ContactUs from "@/components/common/ContactUs/ContactUs";
import NotificationBar from "@/components/common/NotificationBar/NotificationBar";

const pilatWide = localFont({
    src: [
        { path: "../../public/fonts/pilat-wide/PilatWide-Thin.woff2", weight: "100" },
        { path: "../../public/fonts/pilat-wide/PilatWide-Light.woff2", weight: "300" },
        { path: "../../public/fonts/pilat-wide/PilatWide-Regular.woff2", weight: "400" },
        { path: "../../public/fonts/pilat-wide/PilatWide-DemiBold.woff2", weight: "600" },
        { path: "../../public/fonts/pilat-wide/PilatWide-Bold.woff2", weight: "700" },
        { path: "../../public/fonts/pilat-wide/PilatWide-Black.woff2", weight: "900" },
    ],
    variable: "--font-pilat",
});

const reyork = localFont({
    src: [
        {
            path: "../../public/fonts/reyork-fonts/reyork-regular.ttf",
            weight: "400",
            style: "normal",
        },
        {
            path: "../../public/fonts/reyork-fonts/reyork-regular.otf",
            weight: "700",
            style: "normal",
        },
    ],
    variable: "--font-reyork",
});

export const metadata = {
    title: "Vijay Overseas",
    description: "Generated by create next app",
};

const data = {
    start: "2025-01-03",
    end: "2026-01-10",
    heading: "🙏 Remembering Swargiya Vijay Kumar Ji on His Jayanti 🙏",
    description: "His vision and values continue to inspire Hans Heritage's journey",
};

export default function RootLayout({ children }) {
    const now = new Date();
    const startDate = new Date(`${data.start}T00:00:00`);
    const endDate = new Date(`${data.end}T23:59:59`);

    const shouldShow = now >= startDate && now <= endDate;

    return (
        <html lang="en">
            <body className={`${reyork.variable} ${pilatWide.variable}`}>
                {shouldShow && <NotificationBar data={data} />}
                <Navbar shouldShow={shouldShow} />
                {children}
                <ContactUs />
                <Footer />
            </body>
        </html>
    );
}
